name: "dl_feat_prep"

feature_definition:
  feature_type: "both" # options: "norm", "nonorm", "both".

  feature_list: [
            "f_screen:phone_screen_rapids_countepisodeunlock_locmap_exercise:afternoon",
            "f_screen:phone_screen_rapids_countepisodeunlock_locmap_greens:night",
            "f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_exercise:allday",
            "f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_exercise:night",
            "f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_home:night",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise:evening",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_greens:allday",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_greens:night",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_home:night",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_study:evening",
            "f_screen:phone_screen_rapids_mindurationunlock_locmap_exercise:evening",
            "f_screen:phone_screen_rapids_mindurationunlock_locmap_exercise:morning",
            "f_screen:phone_screen_rapids_stddurationunlock_locmap_exercise:evening",
            "f_screen:phone_screen_rapids_stddurationunlock_locmap_home:night",
            "f_screen:phone_screen_rapids_sumdurationunlock_locmap_exercise:night",
            "f_screen:phone_screen_rapids_sumdurationunlock_locmap_home:night",
            "f_screen:phone_screen_rapids_sumdurationunlock_locmap_living:night",
            "f_slp:fitbit_sleep_intraday_rapids_maxdurationasleepunifiedmain:night",
            "f_slp:fitbit_sleep_intraday_rapids_maxdurationawakeunifiedmain:night",
            "f_slp:fitbit_sleep_intraday_rapids_mindurationasleepunifiedmain:afternoon",
            "f_slp:fitbit_sleep_intraday_rapids_mindurationasleepunifiedmain:night",
            "f_slp:fitbit_sleep_intraday_rapids_sumdurationasleepunifiedmain:allday",
            "f_slp:fitbit_sleep_summary_rapids_avgdurationasleepmain:allday",
            "f_slp:fitbit_sleep_summary_rapids_avgdurationinbedmain:allday",
            "f_slp:fitbit_sleep_summary_rapids_lastbedtimemain:allday",
            "f_slp:fitbit_sleep_summary_rapids_sumdurationasleepmain:allday",
            "f_slp:fitbit_sleep_summary_rapids_sumdurationinbedmain:allday",
            "f_steps:fitbit_steps_intraday_rapids_countepisodesedentarybout:evening",
            "f_steps:fitbit_steps_intraday_rapids_maxdurationactivebout:morning",
            "f_steps:fitbit_steps_intraday_rapids_maxsteps:evening",
            "f_steps:fitbit_steps_intraday_rapids_mindurationactivebout:evening",

            "f_loc:phone_locations_doryab_locationentropy_norm:afternoon",
            "f_loc:phone_locations_doryab_loglocationvariance_norm:allday",
            "f_loc:phone_locations_doryab_minlengthstayatclusters_norm:afternoon",
            "f_loc:phone_locations_doryab_outlierstimepercent_norm:morning",
            "f_loc:phone_locations_doryab_radiusgyration_norm:allday",
            "f_screen:phone_screen_rapids_avgdurationunlock_locmap_exercise_norm:evening",
            "f_screen:phone_screen_rapids_avgdurationunlock_locmap_greens_norm:night",
            "f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_exercise_norm:allday",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise_norm:afternoon",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise_norm:evening",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise_norm:night",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_greens_norm:evening",
            "f_screen:phone_screen_rapids_sumdurationunlock_locmap_home_norm:morning",
            "f_slp:fitbit_sleep_intraday_rapids_maxdurationawakeunifiedmain_norm:afternoon",
            "f_slp:fitbit_sleep_intraday_rapids_ratiodurationasleepunifiedwithinmain_norm:afternoon",
            "f_slp:fitbit_sleep_intraday_rapids_ratiodurationawakeunifiedwithinmain_norm:afternoon",
            "f_steps:fitbit_steps_intraday_rapids_countepisodesedentarybout_norm:afternoon",
            "f_steps:fitbit_steps_intraday_rapids_maxdurationsedentarybout_norm:night",
            "f_steps:fitbit_steps_intraday_rapids_stdsteps_norm:morning",
        ]

  feature_list_more_feat_types: [
            "f_screen:phone_screen_rapids_countepisodeunlock_locmap_exercise:afternoon",
            "f_screen:phone_screen_rapids_countepisodeunlock_locmap_greens:night",
            "f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_exercise:allday",
            "f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_exercise:night",
            "f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_home:night",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise:evening",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_greens:allday",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_greens:night",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_home:night",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_study:evening",
            "f_screen:phone_screen_rapids_mindurationunlock_locmap_exercise:evening",
            "f_screen:phone_screen_rapids_mindurationunlock_locmap_exercise:morning",
            "f_screen:phone_screen_rapids_stddurationunlock_locmap_exercise:evening",
            "f_screen:phone_screen_rapids_stddurationunlock_locmap_home:night",
            "f_screen:phone_screen_rapids_sumdurationunlock_locmap_exercise:night",
            "f_screen:phone_screen_rapids_sumdurationunlock_locmap_home:night",
            "f_screen:phone_screen_rapids_sumdurationunlock_locmap_living:night",
            "f_slp:fitbit_sleep_intraday_rapids_maxdurationasleepunifiedmain:night",
            "f_slp:fitbit_sleep_intraday_rapids_maxdurationawakeunifiedmain:night",
            "f_slp:fitbit_sleep_intraday_rapids_mindurationasleepunifiedmain:afternoon",
            "f_slp:fitbit_sleep_intraday_rapids_mindurationasleepunifiedmain:night",
            "f_slp:fitbit_sleep_intraday_rapids_sumdurationasleepunifiedmain:allday",
            "f_slp:fitbit_sleep_summary_rapids_avgdurationasleepmain:allday",
            "f_slp:fitbit_sleep_summary_rapids_avgdurationinbedmain:allday",
            "f_slp:fitbit_sleep_summary_rapids_lastbedtimemain:allday",
            "f_slp:fitbit_sleep_summary_rapids_sumdurationasleepmain:allday",
            "f_slp:fitbit_sleep_summary_rapids_sumdurationinbedmain:allday",
            "f_steps:fitbit_steps_intraday_rapids_countepisodesedentarybout:evening",
            "f_steps:fitbit_steps_intraday_rapids_maxdurationactivebout:morning",
            "f_steps:fitbit_steps_intraday_rapids_maxsteps:evening",
            "f_steps:fitbit_steps_intraday_rapids_mindurationactivebout:evening",
            "f_blue:phone_bluetooth_doryab_uniquedevicesown:night",
            "f_call:phone_calls_rapids_incoming_distinctcontacts:afternoon",

            "f_loc:phone_locations_doryab_locationentropy_norm:afternoon",
            "f_loc:phone_locations_doryab_loglocationvariance_norm:allday",
            "f_loc:phone_locations_doryab_minlengthstayatclusters_norm:afternoon",
            "f_loc:phone_locations_doryab_outlierstimepercent_norm:morning",
            "f_loc:phone_locations_doryab_radiusgyration_norm:allday",
            "f_screen:phone_screen_rapids_avgdurationunlock_locmap_exercise_norm:evening",
            "f_screen:phone_screen_rapids_avgdurationunlock_locmap_greens_norm:night",
            "f_screen:phone_screen_rapids_firstuseafter00unlock_locmap_exercise_norm:allday",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise_norm:afternoon",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise_norm:evening",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_exercise_norm:night",
            "f_screen:phone_screen_rapids_maxdurationunlock_locmap_greens_norm:evening",
            "f_screen:phone_screen_rapids_sumdurationunlock_locmap_home_norm:morning",
            "f_slp:fitbit_sleep_intraday_rapids_maxdurationawakeunifiedmain_norm:afternoon",
            "f_slp:fitbit_sleep_intraday_rapids_ratiodurationasleepunifiedwithinmain_norm:afternoon",
            "f_slp:fitbit_sleep_intraday_rapids_ratiodurationawakeunifiedwithinmain_norm:afternoon",
            "f_steps:fitbit_steps_intraday_rapids_countepisodesedentarybout_norm:afternoon",
            "f_steps:fitbit_steps_intraday_rapids_maxdurationsedentarybout_norm:night",
            "f_steps:fitbit_steps_intraday_rapids_stdsteps_norm:morning",
            "f_blue:phone_bluetooth_doryab_countscansmostfrequentdeviceacrossdatasetown_norm:night",
            "f_call:phone_calls_rapids_outgoing_count_norm:afternoon",
        ]

